# Service Configuration File.
---
name: RPC.AccountService
version: 1.2.0
description: A service for authority, authorization and account details.

main: src/index.js

configurations:
  - name: service
    watch: true
    key: /config/services/AccountService
      # sponsorTableName
      # clientTableName

  - name: shared
    watch: true
    key: /config/shared
      # region
      # cacheEndpoint
      # logLevel
