# Service Configuration File.
---
name: RPC.AccountService
version: 0.0.1
description: A service for authority, authorization and account details.

main: src/index.js

configurations:
  - name: config
    watch: true
    key: /config/services/AccountService
      # sponsorTableName
      # clientTableName

  - name: shared
    watch: true
    key: /config/shared
      # region
